#!/bin/bash

### CUSTOMIZE THE BELOW SETTINGS #######################

# Set ORGNAME to be a very brief name to identify your organization,
# for example "Univ of Wisconsin".
ORGNAME="zsebenik"

# Set CONDORADMIN to be the email address of the Condor Administrator
# at your site.
CONDORADMIN="zsebenik@fgg.uni-lj.si"

# Set POOL to the hostname of the machine running the Condor
# Collector with history statistics enabled.
POOL=127.0.0.1

# Set VIEWDIR to be the directory where you unpacked Java CondorView.
# It is likely to be the directory where this file you are now editing
# is located.
VIEWDIR="/home/sebenik/Projects/www/condor_view"

# Set STATSDIR to be the _directory_ which contains the condor_stats binary.
STATSDIR="/usr/bin"

# Set PATH so it includes the directories which contain awk, bc, 
# sed, date, and condor_stats.
PATH=/bin:/usr/bin:$STATSDIR:/s/std/bin

########### END OF CUSTOMIZATION #######################

# No need to edit anything below unless you know what you are doing.

export POOL
export VIEWDIR
export PATH

cd $VIEWDIR
mkdir -p data/{machine,user}

if [ $# -eq 0 ]; then
	./make_machine_stats hour
	./make_machine_stats day
	./make_machine_stats week
	./make_machine_stats month
	./make_user_stats hour
	./make_user_stats day
	./make_user_stats week
	./make_user_stats month
else
	./make_machine_stats $*
	./make_user_stats $*
fi

VIEWDIR=${VIEWDIR//[\/]/\\/}
sed "s/VIEWDIR/$VIEWDIR/g" cronentries.skel >cronentries
. ./make_page

exit 0
